<?php

/**
 * @file
 * Contains hooks for the module.
 */

/**
 * Implements hook_theme().
 */
function diff_plus_theme() {
  return [
    'diff_plus_ui' => [
      'variables' => [
        'entity' => NULL,
        'from_revision' => NULL,
        'to_revision' => NULL,
        'from_revision_url' => NULL,
        'to_revision_url' => NULL,
        'from_revision_author' => NULL,
        'to_status' => NULL,
        'from_status' => NULL,
        'to_revision_author' => NULL,
        'previous_revision_url' => NULL,
        'next_revision_url' => NULL,
        'version_history_url' => NULL,
        'settings' => NULL,
      ],
    ],
  ];
}
